version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
      - ./mql5_forge_repos:/app/mql5_forge_repos
    command: python backend/main.py
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:8001
    depends_on:
      - backend
    restart: always

volumes:
  node_modules: 